services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT:-5432}
      API_ADDR: ${API_ADDR:-:8075}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
